server:
  port: 3032
  error:    whitelabel:      enabled: false
  
spring:
  application:
    name: microservice-java-service-users
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  h2:    console:      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/service_users_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:    show-sql: true    hibernate:
      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:3031}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
ribbon:
  eureka:
    enabled: true

app:
  properties:
    secret_signature: SecretSignYmotse
    token_expiration_minutes: 60
    

